### PR TITLE
Auto Test PR with GitHub Actions: and Add Makefile for Build 

### LINKED ISSUE #8: Automate Pull Request Code Format Validations & Fixes with GitHub Actions
**Is your feature request related to a problem? Please describe.**
Whenever a pull request is made, if it was edited using Obsidian (preferably/probably), it will contain [incompatible markdown styles][markdown-compatibility] that need fixing or changing before it's ready to go. GitHub doesn't render these properly. Additionally, there are specific naming conventions tied to the Obsidian graph system.

[markdown-compatibility]: https://github.com/Domenic-MZS/Essential-ARscape/pull/7#issuecomment-1837564858

**Describe the Solution You'd Like**
I propose implementing a quick markdown style validation using GitHub's flavor of markdown to streamline the collaboration process. This specific check would make it easier and faster to:
- Identify incorrect filenames, such as missing `README` files or space-separated files.
- Identify incorrect paths in links and tags, such as paths referring to a local drive location like `C:\path\to\file.md`.

To achieve this, it's probably needed a `RegExp` to peek on every file and a script to automatically fix those issues if possible.

**Describe Alternatives You've Considered**
I've considered automating this process post-merge, but I believe a Pull Request validator would be a more robust solution.

**Additional Context**
- [First Obsidian/Markdown PR Request](../pull/7) describing the compatibility issues and editing experience.

### PR DESCRIPTION
**Pull request by Domenic-MZS**
# Auto Test PR with GitHub Actions: and Add Makefile for Build 
This PR closes #8.

## Overview
 - **Issue:** Missing auto-validation on pull requests for running test files and lacking file compilers for Obsidian.
 - **Background:** Working between Obsidian and GitHub flavors reveals issues related to the markdown flavor each one uses. These differences can cause compatibility issues, necessitating manual intervention to rectify them. Therefore, a GitHub action is needed to automatically validate each pull request, highlighting differences for manual resolution or by executing the necessary build scripts.
 - **Solutions:** A similar solution was previously implemented for cross-flavor link conversion at #7.
 - **Impact:** This enhancement aims to reduce review time by eliminating extra manual steps in formatting. It provides a rapid response to collaborators and reviewers regarding any constraints or errors related to the flavor or project requirements.

## Description
This PR introduces a Makefile to simplify the usage of scripts and test files. It facilitates full file and link conversion to the required build format in one operation, improving the overall experience by providing an easier way to automatically execute all necessary conversion files and tests.

**Makefile options include:**
 - `make test`: Run all tests.
 - `make test-{file-name}`: Run a specific test file.
 - `make obsidian`: Convert all files to adhere better on the Obsidian flavor.
 - `make github`: Reverts all files conversions back to the GitHub flavor.

Something important to note out, is that i added some reserved words on the converted files to be able to revert it back later, these are:
 - `.h`: Indicates that the file was a `README` (inspired from [header files in C](https://www.tutorialspoint.com/cprogramming/c_header_files.htm) as it is the "header readme")
 - `.u`: Indicates that the file was and should be a [snake_case](https://es.wikipedia.org/wiki/Snake_case).

> README files will be renamed with their H1 tag (#) followed by the `.h` utility.

## Changes Made
 - Added GitHub Action on PR to run all test files.
    - Executes all test files and exits on the first error.
    
 - Added `test/` files for validation purposes:
    - Ensure all folders have a `README`.
    - Validate that all files follow the project naming convention (snake-case, camel-case, kebab).
    - Confirm that all links use the local path (starting with `/` or `./`).
    - Ensure all `src` attributes follow the same `Links` convention.
  
- Refactor `scripts` & `test` shell files to be [POSIX compliant](https://betterprogramming.pub/24-bashism-to-avoid-for-posix-compliant-shell-scripts-8e7c09e0f49a)

## Notes and References
 - [GitHub Actions Guide](https://docs.github.com/en/actions)
 - [Makefile Guide](https://www.gnu.org/software/make/manual/make.html)
 - [POSIX-like Terminal Issues with Bashisms](https://betterprogramming.pub/24-bashism-to-avoid-for-posix-compliant-shell-scripts-8e7c09e0f49a)
 - [checkbashisms CLI tool](https://man.archlinux.org/man/checkbashisms.1.en)

### CODE REVIEW

**Comment by Domenic-MZS** [comment]
@Mobinake, feel free to review these changes. I have not tested them in a `Windows` environment. It is very likely that they will fail or crash, as paths are not handled very well...

**Comment by Domenic-MZS** [comment]
But as far as i tried, they work fine on fine on Linux. I think another improvement would be to always use lower case names except for obsidian, forcing an uppercase for the first character... I don't think if this is that important to be applied here, what do you think about it?

**Comment by Domenic-MZS** [comment]
It may not be a good idea tho, cause that would break on some files like the `CONTRIBUTING` or `CODE_OF_CONDUCT`

**Review by Domenic-MZS — COMMENTED** [review]
LGTM 🙌🏼

**Review by Mobinake — APPROVED** [review]
good

**Pull request merged**
